### ISSUE TITLE
Keep around old releases on PyPI

### ISSUE THREAD

**Issue by kynan** [charlesflynn/eve-docs#12]
It would be great to have access to old releases via PyPI rather than only the latest release. Imagine you specify a specific version in your `requirements.txt` requirements installation will fail once a new release has been pushed and the old replaced.

**Comment by charlesflynn** [comment]
When I was working on #11 yesterday, I checked the [simple index](https://pypi.python.org/simple/Eve-docs/) and the older releases were there, so I think pip etc should have been okay all along. But I do need to upload 0.1.3 again since its tarfile strangely vanished. 

I just went in and "unhid" the older releases, so they should be visible now on [regular PyPI](https://pypi.python.org/pypi/Eve-docs).

**Comment by charlesflynn** [comment]
Okay 0.1.3 is uploaded now, so all the older versions should be visible

**Comment by kynan** [comment]
Great, thanks!
